### PR TITLE
Add Traditional Chinese Translation

### PR DESCRIPTION
**Pull request by FangkuaiYa**
Add Traditional Chinese Translation
添加繁体中文翻译

### CODE REVIEW

**Comment by yukieiji** [comment]
Thanks for the PR.
The automatic translation check didn't support TChinese, so I checked manually and found the following translations missing.
Should I merge this?

 - FileName:ExtremeRolesTransData.xlsx

| Languages | Missing TransKeys |
| --- | --- |
| TChinese | Moderator |
| TChinese | ModeratorSpawnRate |
| TChinese | ModeratorRoleNum |
| TChinese | ModeratorHasOtherVision |
| TChinese | ModeratorVision |
| TChinese | ModeratorApplyEnvironmentVisionEffect |
| TChinese | ModeratorAwakeTaskGage |
| TChinese | ModeratorAbilityCoolTime |
| TChinese | ModeratorAbilityCount |
| TChinese | ModeratorMeetingTimerOffset |
| TChinese | ModeratorIntroDescription |
| TChinese | ModeratorShortDescription |
| TChinese | ModeratorFullDescription |
| TChinese | changeMeetingTime |
| TChinese | moderate |
| TChinese | Psychic |
| TChinese | PsychicSpawnRate |
| TChinese | PsychicRoleNum |
| TChinese | PsychicHasOtherVision |
| TChinese | PsychicVision |
| TChinese | PsychicApplyEnvironmentVisionEffect |
| TChinese | PsychicAwakeTaskGage |
| TChinese | PsychicAwakeDeadPlayerNum |
| TChinese | PsychicAbilityCoolTime |
| TChinese | PsychicAbilityActiveTime |
| TChinese | PsychicAbilityCount |
| TChinese | PsychicIsUpgradeAbility |
| TChinese | PsychicUpgradeTaskGage |
| TChinese | PsychicUpgradeDeadPlayerNum |
| TChinese | PsychicIntroDescription |
| TChinese | PsychicShortDescription |
| TChinese | PsychicFullDescription |
| TChinese | PsychicPsychic |
| TChinese | PsychicPsychicStart |
| TChinese | PsychicPsychicEnd |
| TChinese | PsychicPsychicResult |
| TChinese | PsychicPsychicStrAliveRole |
| TChinese | PsychicPsychicStrTeam |
| TChinese | PsychicPsychicStrForAliveNum |
| TChinese | Bait |
| TChinese | BaitSpawnRate |
| TChinese | BaitRoleNum |
| TChinese | BaitHasOtherVision |
| TChinese | BaitVision |
| TChinese | BaitApplyEnvironmentVisionEffect |
| TChinese | BaitAwakeTaskGage |
| TChinese | BaitDelayUntilForceReport |
| TChinese | BaitEnableBaitBenefit |
| TChinese | BaitKillCoolReduceMulti |
| TChinese | BaitReduceTimer |
| TChinese | BaitIntroDescription |
| TChinese | BaitShortDescription |
| TChinese | BaitFullDescription |
| TChinese | forceReportUntil |
| TChinese | UseRaiseHand |
| TChinese | VentAnimationModeInVison |
| TChinese | VanillaAnimation |
| TChinese | DonotWallHack |
| TChinese | DonotOutVison |
| TChinese | IsFixWallHaskTask |
| TChinese | GarbageTask |
| TChinese | ShowerTask |
| TChinese | DevelopPhotosTask |
| TChinese | DivertPowerTask |
| TChinese | EnableSpecialSetting |
| TChinese | SkeldRandomSpawn |
| TChinese | MiraHqRandomSpawn |
| TChinese | PolusRandomSpawn |
| TChinese | AirShipRandomSpawn |
| TChinese | FungleRandomSpawn |
| TChinese | PublicBetaMode |
| TChinese | SystemMessage |
| TChinese | SuccessAmongUsConnect |
| TChinese | InputMessage |
| TChinese | DisconectAmongUsMessage |
| TChinese | ConectSocketMessage |
| TChinese | InvalidCharMessage |
| TChinese | PublicBetaStr |
| TChinese | PublicBetaEnableDisableStr |
| TChinese | PublicBetaWarning |
| TChinese | PublicBetaReboot |
| TChinese | DefaultSpawn |
| TChinese | EnableKey |
| TChinese | DisableKey |
| TChinese | SubmergedSubmergedSpawnSetting |
| TChinese | LowerCentralOnly |
| TChinese | UpperCentralOnly |
| TChinese | PsychoKillerIsForceRestartWhenMeetingEnd |
| TChinese | PsychoKillerIsDiactiveUntilKillWhenMeetingEnd |
| TChinese | UnderWarperWallHackVent |
| TChinese | Thief |
| TChinese | ThiefSpawnRate |
| TChinese | ThiefRoleNum |
| TChinese | ThiefHasOtherVision |
| TChinese | ThiefVision |
| TChinese | ThiefApplyEnvironmentVisionEffect |
| TChinese | ThiefHasOtherKillCool |
| TChinese | ThiefKillCoolDown |
| TChinese | ThiefHasOtherKillRange |
| TChinese | ThiefKillRange |
| TChinese | ThiefAbilityCoolTime |
| TChinese | ThiefAbilityActiveTime |
| TChinese | ThiefAbilityCount |
| TChinese | ThiefRange |
| TChinese | ThiefSetNum |
| TChinese | ThiefSetTimeOffset |
| TChinese | ThiefPickUpTimeOffset |
| TChinese | ThiefIsAddEffect |
| TChinese | ThiefIntroDescription |
| TChinese | ThiefShortDescription |
| TChinese | ThiefFullDescription |
| TChinese | steal |
| TChinese | Crewshroom |
| TChinese | CrewshroomSpawnRate |
| TChinese | CrewshroomRoleNum |
| TChinese | CrewshroomHasOtherVision |
| TChinese | CrewshroomVision |
| TChinese | CrewshroomApplyEnvironmentVisionEffect |
| TChinese | CrewshroomHasOtherKillCool |
| TChinese | CrewshroomKillCoolDown |
| TChinese | CrewshroomHasOtherKillRange |
| TChinese | CrewshroomKillRange |
| TChinese | CrewshroomAbilityCoolTime |
| TChinese | CrewshroomAbilityCount |
| TChinese | CrewshroomDelaySecond |
| TChinese | CrewshroomFungleIntroDescription |
| TChinese | CrewshroomIntroDescription |
| TChinese | CrewshroomShortDescription |
| TChinese | CrewshroomFullDescription |
| TChinese | CrewshroomSet |
| TChinese | Terorist |
| TChinese | TeroristSpawnRate |
| TChinese | TeroristRoleNum |
| TChinese | TeroristHasOtherVision |
| TChinese | TeroristVision |
| TChinese | TeroristApplyEnvironmentVisionEffect |
| TChinese | TeroristHasOtherKillCool |
| TChinese | TeroristKillCoolDown |
| TChinese | TeroristHasOtherKillRange |
| TChinese | TeroristKillRange |
| TChinese | TeroristAbilityCoolTime |
| TChinese | TeroristAbilityCount |
| TChinese | TeroristCanActiveOtherSabotage |
| TChinese | TeroristExplosionTime |
| TChinese | TeroristBombNum |
| TChinese | TeroristPlayerActivateTime |
| TChinese | TeroristCanUseDeadPlayer |
| TChinese | TeroristDeadPlayerActivateTime |
| TChinese | TeroristIntroDescription |
| TChinese | TeroristShortDescription |
| TChinese | TeroristFullDescription |
| TChinese | TeroristBombSet |
| TChinese | TeroristBombTask |
| TChinese | TeroristBombMinigameProgress |
| TChinese | TeroristBombMinigameStart |
| TChinese | QueenServantSucideWithQueenWhenHasKill |
| TChinese | Hatter |
| TChinese | HatterSpawnRate |
| TChinese | HatterRoleNum |
| TChinese | HatterHasOtherVision |
| TChinese | HatterVision |
| TChinese | HatterApplyEnvironmentVisionEffect |
| TChinese | HatterCanRepairSabotage |
| TChinese | HatterWinCount |
| TChinese | HatterAbilityCoolTime |
| TChinese | HatterAbilityCount |
| TChinese | HatterHideMeetingTimer |
| TChinese | HatterMeetingTimerDecreaseLower |
| TChinese | HatterMeetingTimerDecreaseUpper |
| TChinese | HatterIncreaseTaskGage |
| TChinese | HatterIncreseNum |
| TChinese | HatterIntroDescription |
| TChinese | HatterShortDescription |
| TChinese | HatterFullDescription |
| TChinese | timeKill |
| TChinese | Accelerator |
| TChinese | NiceAccelerator |
| TChinese | EvilAccelerator |
| TChinese | AcceleratorSpawnRate |
| TChinese | AcceleratorRoleNum |
| TChinese | AcceleratorIsAssignImposter |
| TChinese | AcceleratorImposterSelectedRate |
| TChinese | AcceleratorHasOtherVision |
| TChinese | AcceleratorVision |
| TChinese | AcceleratorApplyEnvironmentVisionEffect |
| TChinese | AcceleratorHasOtherKillCool |
| TChinese | AcceleratorKillCoolDown |
| TChinese | AcceleratorHasOtherKillRange |
| TChinese | AcceleratorKillRange |
| TChinese | AcceleratorAbilityCoolTime |
| TChinese | AcceleratorAbilityActiveTime |
| TChinese | AcceleratorAbilityCount |
| TChinese | AcceleratorSpeed |
| TChinese | AcceleratorUseOtherPlayer |
| TChinese | AcceleratorIntroDescription |
| TChinese | AcceleratorShortDescription |
| TChinese | AcceleratorFullDescription |
| TChinese | AccelerateSet |

 - FileName:ExtremeSkinsTransData.xlsx

| Languages | Missing TransKeys |
| --- | --- |
| TChinese | errorCannotGameStart |
| TChinese | errorNotInstalled |
| TChinese | errorOldInstalled |
| TChinese | errorNewInstalled |
| TChinese | errorDiffHostVersion |
| TChinese | innerslothMake |
| TChinese | enableCreatorMode |
| TChinese | disableReadyCreatorMode |
| TChinese | enableReadyCreatorMode |
| TChinese | kusaZunGreen |
| TChinese | darkRed |
| TChinese | mediumVioletRed |
| TChinese | mediumPurple |
| TChinese | rosyBrown |
| TChinese | darkMagenta |
| TChinese | olive |
| TChinese | steelBlue |
| TChinese | dodgerBlue |
| TChinese | darkSeaGreen |
| TChinese | sikon |
| TChinese | konjou |
| TChinese | vermilion |
| TChinese | ivyGreen |
| TChinese | tilleul |
| TChinese | ivory |
| TChinese | kenpou |
| TChinese | grisbleu |
| TChinese | melon |
| TChinese | clan |
| TChinese | Shiraaiiro |
| TChinese | whitePink |
| TChinese | thinPurple |
| TChinese | sienna |
| TChinese | lightAvocado |
| TChinese | lightIwaitya |
| TChinese | diardRed |
| TChinese | diardGreen |
| TChinese | diardBlue |
| TChinese | chaos |
| TChinese | inverted |
| TChinese | oddGreen |
| TChinese | tigr |
| TChinese | kigi |

**Comment by yukieiji** [comment]
I merge this for the v10 release. 
If you have any additions, please open PR again.

**Comment by FangkuaiYa** [comment]
I translated TChinese by comparing it with SChinese. I may not have translated some parts of SChinese that were not covered, or I may not have saved them after translation because I checked and I have already translated them all.







                       
原始邮件
                       
                     

发件人："yukieiji"< ***@***.*** &gt;;

发件时间：2024/3/6 22:07

收件人："yukieiji/ExtremeRoles"< ***@***.*** &gt;;

抄送人："Fang-Kaui"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [yukieiji/ExtremeRoles] Add Traditional Chinese Translation (PR#356)




 
Merged #356 into master.

**Comment by yukieiji** [comment]
Ok, I see.

**Pull request merged**
