### PR TITLE
Update for SChinese Translation

### PR DESCRIPTION
**Pull request by ZeMingoh233**

### CODE REVIEW

**Comment by yukieiji** [comment]
GitHub actions do not work properly and must be performed manually

### GitHub Actions MSBuilds

 - Build Result : Success

### Translation Checker Report

 - FileName:ExtremeRolesTransData.xlsx

| Languages | Missing TransKeys |
| --- | --- |
| English | BodyGuardIsReportPlayerName |
| English | BodyGuardReportPlayerMode |
| English | BodyGuardIsBlockMeetingKill |
| English | BodyGuardPlayerNameOnly |
| English | GuardedPlayerNameOnly |
| English | BothPlayerName |
| SChinese | MadmateIsDontCountAliveCrew |
| SChinese | GuesserRoleNum |

 - FileName:ExtremeSkinsTransData.xlsx

| Languages | Missing TransKeys |
| --- | --- |
| SChinese | enableCreatorMode |
| SChinese | disableReadyCreatorMode |
| SChinese | enableReadyCreatorMode |
| SChinese | Shiraaiiro |
| SChinese | whitePink |
| SChinese | thinPurple |
| SChinese | sienna |
| SChinese | lightAvocado |
| SChinese | lightIwaitya |
| SChinese | diardRed |
| SChinese | diardGreen |
| SChinese | diardBlue |
| SChinese | chaos |
| SChinese | inverted |
| SChinese | oddGreen |
| SChinese | tigr |
| SChinese | kigi |

**Comment by yukieiji** [comment]
Do you want to correct these translations now? or later?

**Comment by ZeMingoh233** [comment]
Now these translation has been corrected.
I wish there's no more mistakes now.

**Comment by yukieiji** [comment]
Manually executed, but seems to work fine.
Thank you for the English support too!

### GitHub Actions MSBuilds

 - Build Result : Success

### Translation Checker Report

 - FileName:ExtremeRolesTransData.xlsx

| Languages | Missing TransKeys |
| --- | --- |

 - FileName:ExtremeSkinsTransData.xlsx

| Languages | Missing TransKeys |
| --- | --- |

**Pull request merged**
