### PR TITLE
Update for SChinese Translation

### PR DESCRIPTION
**Pull request by ZeMingoh233**

### CODE REVIEW

**Comment by yukieiji** [comment]
There are a few omissions, can they be corrected by 11:00 (JST)?

### GitHub Actions MSBuilds

 - Build Result : success

### Translation Checker Report

 - FileName:ExtremeRolesTransData.xlsx

| Languages | Missing TransKeys |
| --- | --- |
| English | ConfirmExilMode |
| English | IsConfirmRole |
| English | AllTeam |
| English | CrewExileTextSP |
| English | CrewExileTextSN |
| English | CrewExileTextPP |
| English | CrewExileTextPN |
| English | NeutExileTextSP |
| English | NeutExileTextSN |
| English | NeutExileTextPP |
| English | NeutExileTextPN |
| English | CrewExileTextSPWithRole |
| English | CrewExileTextSNWithRole |
| English | CrewExileTextPPWithRole |
| English | CrewExileTextPNWithRole |
| English | NeutExileTextSPWithRole |
| English | NeutExileTextSNWithRole |
| English | NeutExileTextPPWithRole |
| English | NeutExileTextPNWithRole |
| English | ExileTextAllTeam |
| English | ExileTextAllTeamWithRole |
| English | CrewmateRemainS |
| English | CrewmateRemainP |
| English | NeutralRemainS |
| English | NeutralRemainP |
| English | AllTeamAlive |
| English | Gambler |
| English | GamblerSpawnRate |
| English | GamblerRoleNum |
| English | GamblerHasOtherVision |
| English | GamblerVision |
| English | GamblerApplyEnvironmentVisionEffect |
| English | GamblerNormalVoteRate |
| English | GamblerIntroDescription |
| English | GamblerShortDescription |
| English | GamblerFullDescription |
| English | Teleporter |
| English | TeleporterSpawnRate |
| English | TeleporterRoleNum |
| English | TeleporterHasOtherVision |
| English | TeleporterVision |
| English | TeleporterApplyEnvironmentVisionEffect |
| English | TeleporterCanUseOtherPlayer |
| English | TeleporterAbilityCoolTime |
| English | TeleporterAbilityCount |
| English | TeleporterIntroDescription |
| English | TeleporterShortDescription |
| English | TeleporterFullDescription |
| English | SetPortal |
| English | Slime |
| English | SlimeSpawnRate |
| English | SlimeRoleNum |
| English | SlimeHasOtherVision |
| English | SlimeVision |
| English | SlimeApplyEnvironmentVisionEffect |
| English | SlimeHasOtherKillCool |
| English | SlimeKillCoolDown |
| English | SlimeHasOtherKillRange |
| English | SlimeKillRange |
| English | SlimeAbilityCoolTime |
| English | SlimeAbilityActiveTime |
| English | SlimeIntroDescription |
| English | SlimeShortDescription |
| English | SlimeFullDescription |
| English | SlimeMorph |
| English | Zombie |
| English | ZombieSpawnRate |
| English | ZombieRoleNum |
| English | ZombieHasOtherVision |
| English | ZombieVision |
| English | ZombieApplyEnvironmentVisionEffect |
| English | ZombieHasOtherKillCool |
| English | ZombieKillCoolDown |
| English | ZombieHasOtherKillRange |
| English | ZombieKillRange |
| English | ZombieAwakeKillCount |
| English | ZombieAbilityCoolTime |
| English | ZombieAbilityActiveTime |
| English | ZombieAbilityCount |
| English | ZombieShowMagicCircleTime |
| English | ZombieResurrectKillCount |
| English | ZombieResurrectDelayTime |
| English | ZombieCanResurrectOnExil |
| English | ZombieIntroDescription |
| English | ZombieShortDescription |
| English | ZombieFullDescription |
| English | featMagicCircle |
| English | Mover |
| English | NiceMover |
| English | EvilMover |
| English | MoverSpawnRate |
| English | MoverRoleNum |
| English | MoverIsAssignImposter |
| English | MoverImposterSelectedRate |
| English | MoverHasOtherVision |
| English | MoverVision |
| English | MoverApplyEnvironmentVisionEffect |
| English | MoverHasOtherKillCool |
| English | MoverKillCoolDown |
| English | MoverHasOtherKillRange |
| English | MoverKillRange |
| English | MoverAbilityCoolTime |
| English | MoverAbilityActiveTime |
| English | MoverAbilityCount |
| English | MoverIntroDescription |
| English | MoverShortDescription |
| English | MoverFullDescription |
| English | Moving |
| English | Shutter |
| English | ShutterSpawnRate |
| English | ShutterRoleNum |
| English | ShutterPhotoRange |
| English | ShutterRightPlayerNameRate |
| English | ShutterAbilityCoolTime |
| English | ShutterIsReportAbility |
| English | ShutterAbilityCount |
| English | ShutterShortDescription |
| English | ShutterFullDescription |
| English | ShutterTakePhotoButton |
| English | ShutterTakePhoto |
| English | smokingThisName |
| English | ShutterTakePhotoReport |
| English | Igniter |
| English | IgniterSpawnRate |
| English | IgniterRoleNum |
| English | IgniterAbilityCoolTime |
| English | IgniterAbilityActiveTime |
| English | IgniterIsReportAbility |
| English | IgniterAbilityCount |
| English | IgniterIsEffectImpostor |
| English | IgniterIsEffectNeutral |
| English | IgniterShortDescription |
| English | IgniterFullDescription |
| English | IgniterSwitchLightButton |
| English | IgniterSwitchLight |
| English | Foras |
| English | ForasSpawnRate |
| English | ForasRoleNum |
| English | ForasRange |
| English | ForasMissingTargetRate |
| English | ForasDelayTime |
| English | ForasAbilityCoolTime |
| English | ForasAbilityActiveTime |
| English | ForasIsReportAbility |
| English | ForasAbilityCount |
| English | ForasShortDescription |
| English | ForasFullDescription |
| English | ForasShowArrowButton |
| English | ForasShowArrow |
| SChinese | ConfirmExilMode |
| SChinese | IsConfirmRole |
| SChinese | AllTeam |
| SChinese | CrewExileTextSP |
| SChinese | CrewExileTextSN |
| SChinese | CrewExileTextPP |
| SChinese | CrewExileTextPN |
| SChinese | NeutExileTextSP |
| SChinese | NeutExileTextSN |
| SChinese | NeutExileTextPP |
| SChinese | NeutExileTextPN |
| SChinese | CrewExileTextSPWithRole |
| SChinese | CrewExileTextSNWithRole |
| SChinese | CrewExileTextPPWithRole |
| SChinese | CrewExileTextPNWithRole |
| SChinese | NeutExileTextSPWithRole |
| SChinese | NeutExileTextSNWithRole |
| SChinese | NeutExileTextPPWithRole |
| SChinese | NeutExileTextPNWithRole |
| SChinese | ExileTextAllTeam |
| SChinese | ExileTextAllTeamWithRole |
| SChinese | CrewmateRemainS |
| SChinese | CrewmateRemainP |
| SChinese | NeutralRemainS |
| SChinese | NeutralRemainP |
| SChinese | AllTeamAlive |
| SChinese | Moving |

 - FileName:ExtremeSkinsTransData.xlsx

| Languages | Missing TransKeys |
| --- | --- |

**Comment by ZeMingoh233** [comment]
Sorry I got up late and missed the agreed time.
I've finished the missing SChinese translation. As for the English translation, I think I'd better not butt in.

**Comment by yukieiji** [comment]
Thanks for the update,
As for the English translation, another person is in charge of that, so it isn't a problem.

**Comment by yukieiji** [comment]
I have confirmed the updates and merge them in.

**Pull request merged**
