### PR TITLE
5.1.0.0 ENG translation update

### PR DESCRIPTION
**Pull request by yuhgao**
## issueへのリンク
#252 

## レビュワーに確認してほしいこと
・意図と違う翻訳が存在しないか。
・Excelが最新版と整合するか否か。

以下、変更点のまとめになります。
[ExRoles_Eng_20230209.xlsx](https://github.com/yukieiji/ExtremeRoles/files/10692980/ExRoles_Eng_20230209.xlsx)

## チェックリスト
コードに変更はありません。
- [] : ホストで追加する機能や役職、能力が使えることを確認した
- [] : ホスト以外で追加する機能や役職、能力が使えることを確認した
- [] : 役職の能力に関して会議が挟まる、サイドキックにされる等で正しくリセットされることを確認した

### 追加チェックリスト
コードに変更はありません。
- [] : 変数名に代入される値は妥当であるか
- [] : メソッド、関数名に相応しくない処理をしていないか
- [] : メソッド、関数は長くなりすぎてないか
- [] : 機能や役職の変数、メソッドのアクセシビリティレベルは妥当であるか(publicを多用していないか)
- [] : 機能や役職のデータ構造は妥当だと思われるものを使用しているか

### CODE REVIEW

**Comment by yukieiji** [comment]
まだGitHub周りでうまくいかないので手動で実行してます

### GitHub Actions MSBuilds

 - Build Result : Success

### Translation Checker Report

 - FileName:ExtremeRolesTransData.xlsx

| Languages | Missing TransKeys |
| --- | --- |
| SChinese | AirShipEnableAdmin |
| SChinese | ModeBoth |
| SChinese | ModeCockpitOnly |
| SChinese | ModeArchiveOnly |
| SChinese | IsAutoSelectRandomSpawn |
| SChinese | yourNoAssignGhostRole |
| SChinese | SheriffIsSyncTaskAndShootNum |
| SChinese | SheriffSyncShootTaskGage |
| SChinese | BodyGuardShieldRange |
| SChinese | BodyGuardAbilityCoolTime |
| SChinese | BodyGuardAbilityCount |
| SChinese | BodyGuardIntroDescription |
| SChinese | BodyGuardShortDescription |
| SChinese | BodyGuardFullDescription |
| SChinese | shield |
| SChinese | resetShield |
| SChinese | meetingShieldState |
| SChinese | FakerIntroDescription |
| SChinese | FakerShortDescription |
| SChinese | FakerFullDescription |
| SChinese | dummyDeadBody |
| SChinese | dummyPlayer |
| SChinese | DummyPlayerName |
| SChinese | OverLoaderAwakeImpostorNum |
| SChinese | OverLoaderAwakeKillCount |
| SChinese | HypnotistAwakeKillCount |
| SChinese | Magician |
| SChinese | MagicianSpawnRate |
| SChinese | MagicianRoleNum |
| SChinese | MagicianHasOtherVison |
| SChinese | MagicianVison |
| SChinese | MagicianApplyEnvironmentVisionEffect |
| SChinese | MagicianHasOtherKillCool |
| SChinese | MagicianKillCoolDown |
| SChinese | MagicianHasOtherKillRange |
| SChinese | MagicianKillRange |
| SChinese | MagicianAbilityCoolTime |
| SChinese | MagicianTeleportTargetRate |
| SChinese | MagicianDupeTeleportTargetTo |
| SChinese | MagicianIncludeSpawnPoint |
| SChinese | MagicianIncludeRolePlayer |
| SChinese | MagicianIntroDescription |
| SChinese | MagicianShortDescription |
| SChinese | MagicianFullDescription |
| SChinese | juggling |
| SChinese | MadmateIsDontCountAliveCrew |
| SChinese | Delinquent |
| SChinese | Wisp |
| SChinese | KidsSpawnRate |
| SChinese | KidsRoleNum |
| SChinese | KidsIsMultiAssign |
| SChinese | DelinquentHasOtherVison |
| SChinese | DelinquentVison |
| SChinese | DelinquentApplyEnvironmentVisionEffect |
| SChinese | DelinquentRange |
| SChinese | DelinquentAbilityCoolTime |
| SChinese | DelinquentAbilityCount |
| SChinese | WispTorchAbilityNum |
| SChinese | WispWinNum |
| SChinese | WispTorchNum |
| SChinese | WispTorchRange |
| SChinese | WispTorchActiveTime |
| SChinese | WispBlackOutTime |
| SChinese | WispAbilityCoolTime |
| SChinese | WispIsReportAbility |
| SChinese | DelinquentIntroDescription |
| SChinese | DelinquentShortDescription |
| SChinese | DelinquentFullDescription |
| SChinese | scribble |
| SChinese | selfBomb |
| SChinese | WispShortDescription |
| SChinese | WispFullDescription |
| SChinese | WispSetTorchButton |
| SChinese | WispSetTorch |
| SChinese | scribeText |
| SChinese | Buddy |
| SChinese | BuddySpawnRate |
| SChinese | BuddyAssignsNum |
| SChinese | BuddyRoleNum |
| SChinese | BuddyHasOtherVison |
| SChinese | BuddyVison |
| SChinese | BuddyApplyEnvironmentVisionEffect |
| SChinese | BuddyIsMultiAssign |
| SChinese | BuddyAwakeTaskGage |
| SChinese | BuddyIntroDescription |
| SChinese | BuddyShortDescription |
| SChinese | BuddyFullDescription |
| SChinese | Guesser |
| SChinese | NiceGuesser |
| SChinese | EvilGuesser |
| SChinese | GuesserSpawnRate |
| SChinese | GuesserRoleNum |
| SChinese | GuesserIsAssignImposter |
| SChinese | GuesserImposterSelectedRate |
| SChinese | GuesserHasOtherVison |
| SChinese | GuesserVison |
| SChinese | GuesserApplyEnvironmentVisionEffect |
| SChinese | GuesserHasOtherKillCool |
| SChinese | GuesserKillCoolDown |
| SChinese | GuesserHasOtherKillRange |
| SChinese | GuesserKillRange |
| SChinese | GuesserCanCallMeeting |
| SChinese | GuesserGuessNum |
| SChinese | GuesserMaxGuessNumWhenMeeting |
| SChinese | GuesserCanGuessNoneRole |
| SChinese | GuesserGuessNoneRoleMode |
| SChinese | BothGuesser |
| SChinese | NiceGuesserOnly |
| SChinese | EvilGuesserOnly |
| SChinese | GuesserIntroDescription |
| SChinese | GuesserShortDescription |
| SChinese | GuesserFullDescription |
| SChinese | guesserUiTitle |
| SChinese | guesserUiInfo |
| SChinese | guesserConfirmMenu |
| SChinese | PoltergeistAbilityCount |

 - FileName:ExtremeSkinsTransData.xlsx

| Languages | Missing TransKeys |
| --- | --- |
| SChinese | enableCreatorMode |
| SChinese | disableReadyCreatorMode |
| SChinese | enableReadyCreatorMode |
| SChinese | Shiraaiiro |
| SChinese | whitePink |
| SChinese | thinPurple |
| SChinese | sienna |
| SChinese | lightAvocado |
| SChinese | lightIwaitya |
| SChinese | diardRed |
| SChinese | diardGreen |
| SChinese | diardBlue |
| SChinese | chaos |
| SChinese | inverted |
| SChinese | oddGreen |
| SChinese | tigr |
| SChinese | kigi |

**Comment by yukieiji** [comment]
レビューしました

- AliceFullDescription 
  - Be KILLED by an IMPOSTOR => Be KILLED by ONLY IMPOSTORs
      - インポスターは単体ではないのとインポスターのみであることを強調する
- JesterFullDescription
  - A NEUTRAL role => ニュートラル役職以外の説明がないですが大丈夫ですか
    - 他の役職は説明がついているため確認です
  -  STATS may show the Jester as alive from game latency or other circumstances. => STATS may show the Jester as alive from lag.
    - ゲームのレイテシよりラグで統一したほうがわかりやすいかな？
- YandereFullDescription
  - No IMPOSTERs and NEUTRALs with abilities to KILL or make you die are alive (exept your LOVER) => No IMPOSTERs and NEUTRALs with abilities to KILL or make you die are alive (exept your SWEETIE)
     - 他の表現と同じくSWEETIEに統一
- YokoFullDescription
  - Be alive when an other team achives their means of victory. => Be alive when an other team victory
    - 簡略化
  - All players assigned to this role can win together => All players who this role can victory together
    - 簡略化とvictoryに統一
- EaterFullDescription
  - EAT and VORE a set amount of players/corpses. => EAT and VORE a set amount of players/dead bodies.
    - AmongUs公式のdead bodieに統一
- MarlinFullDescription
  - A CREWMATE role knowing who's the bad guys => A CREWMATE role knowing who's IMPOSTORs (and NEUTRALs when option enable)
    - 明記化
- AssassinFullDescription
  -  An IMPOSTOR role with an additional chance to achive victory! => An IMPOSTOR role with an additional chance to new victory!
     - 新しい勝利条件であることを明記

- HeroFullDescription
  -  LEVEL 1 - Nullifies KILLs from Impostors. => LEVEL 1 - Block KILL(only KILL Button) from IMPOSTORs.
    - キルボタンのキルを無効化することと、他の文章と同じくImpostorを大文字化かつNullifiesをBlockに変更
- VigilanteCrewDescription、VigilanteImpDescription、VigilanteNeutDescription
  - MISSION 1も記載するならMISSON 2も達成できると思われるのでそちらも記載すべきかと
- DetectiveFullDescription
  - After a dead body is reported, the reported position is assigned as a "Crime site". => After a dead body is reported, the position what reported dead body's player killed is assigned as a "Crime site".
    - 通報位置ではなくキルされた位置なので修正
- SupporterFullDescription、SupporterImposterFullDescription
  - ～ is present => ～ is assigned 

- 以下は確認です
  - クイーンの勝利条件周りの説明にあるKINGDOM周りは必要ないような気もしなくないです(フレーバーテキスト感が強い)

**Comment by yuhgao** [comment]
いただいたものをもとに修正いたしました。

Alice:注釈を追加
*Being KILLed by other teams/players exept Impostors does not achieve MISSION 1.

Jester:ロール名の説明を追加、レイテンシーとラグを併記
*STATS may show the Jester as alive from game latencies/lags.

Yandere:修正漏れ。また排除すべきがKILLボタンをもつプレーヤーだけではないので文言を修正（キル能力≒KILLボタン）
  2. Eliminate all other IMPOSTORS / NEUTRALS with abilities to eliminate players (i.e. KILL, Propagate) exept your SWEETIE.

Traitor:ヤンデレに準拠（キル能力≒KILLボタン）

Youko:簡略化と表記改善
MISSION : Be alive when an other team achives victory.
(All players with this role wins together)

Eater:Dead body/bodiesに統一

Merlin:他の役職に準じて二行目に役職能力の詳細を追加
Can know who the IMPOSTORS (and NEUTRALS when the configuration is on) are.

Assasin:「Brand-new」を追加
An IMPOSTOR role with a brand-new additional chance to achive victory!

Hero:インポスター以外によるキル・死亡が通るように注釈
  - Does not nullify NEUTRAL KILLs and non-KILL deaths (i.e. Missionary's Propagation)

Vigilante:勝利条件２を明記、2-EXをEXに変更

Detective:修正
 - After a dead body is reported, the reported body's position is assigned as a "Crime site".

Supporter/SupporterImpostor:Assignedに修正

Queen:KINGDOM→teamに修正
MISSION: Halve the remaining players with your own team, and eliminate all other IMPOSTORS / NEUTRALS with abilities to eliminate players (i.e. KILL, Propagate).

以上ご確認お願いいたします。

**Comment by yukieiji** [comment]
IMPOSTORsとIMPOSTORS、NEUTRALsとNEUTRALSが混在しているのでどちらかに統一
PropagateとMissionary's Propagationが混在してるのでどちらかに統一、Propagateが能力なので大文字化

> Hero:インポスター以外によるキル・死亡が通るように注釈

ヒーローの防御はインポスターからの"キルボタンによるキル"のみでシューターのシュート等の特殊キルは防げないのでKILLで統一するのは危ないような気がします

**Comment by yuhgao** [comment]
IMPOSTORs→IMPOSTORS, NEUTRALs→NEUTRALS, Propagation → PROPAGATEに統一しました。

Combination: B158(Lover):修正漏れです。本来はTraitorに準拠し特殊キル持ちも明記するはずなので修正しました。また人数減少による自殺に付いての文章の文法ミスを修正。

Hero B72:注釈に「インポスターによるKILLボタンでないキル」の例としてシューターを追加するかたちでいかがでしょう？
  - Does not nullify NEUTRAL KILLs and non-KILL deaths (i.e. Shooter's "SHOOT", Missionary's "PROPAGATE")

**Comment by yukieiji** [comment]
> Does not nullify NEUTRAL KILLs and non-KILL deaths (i.e. Shooter's "SHOOT", Missionary's "PROPAGATE")

キルとデスがダブってるのでこうはどうでしょうか
Does not nullify NEUTRAL KILLs and ability KILL (i.e. Shooter's "SHOOT", Missionary's "PROPAGATE")

**Comment by yuhgao** [comment]
現状AmongusだとKILLがアビリティ扱い（Wikiなどの表記による）なので、KILL＝キルボタンとして翻訳しています。なのでElimination（プレイヤー排除）、non-KILL death（キルボタンでない殺害）という表現を使っているのですが、ability KILLだとKILL Abilityと混同されないでしょうか。

**Comment by yukieiji** [comment]
> 現状AmongusだとKILLがアビリティ扱い（Wikiなどの表記による）なので、KILL＝キルボタンとして翻訳しています。なのでElimination（プレイヤー排除）、non-KILL death（キルボタンでない殺害）という表現を使っているのですが、ability KILLだとKILL Abilityと混同されないでしょうか。

キルボタンでない殺害ってのが通じにくい気がするような気もしなくはないです
ここの文章だけKILLのダブルミーニングが邪魔してる気がするのでKillを小文字にしてIMPOSTOR ability's kill(exclude kill button)とかどうでしょうか？

**Comment by yuhgao** [comment]
なるほど、確かにキルボタンでないキルっていう言い方は混同しやすいですね
Does not nullify NEUTRAL KILLs and other player-eliminating abilities (i.e. Shooter's "SHOOT", Missionary's "PROPAGATE")
であればどうでしょうか。

**Comment by yukieiji** [comment]
問題なさそうです更新をお願いします

**Comment by yuhgao** [comment]
更新いたしました！

**Pull request merged**
